#!/bin/sh

# Mercurial pretxncommit hook
echo "Performing jslint check on modified js resources"
for i in $(hg log -r $HG_NODE --template '{files}'); do echo $i | awk '/.js$/ && ! /^web/' | xargs -rn1 ./modules/org.openbravo.client.kernel/jslint/jslint || exit 1; done;
