#!/bin/sh
echo "Performing jslint check on all js resources"
find -name '*.js' -and ! -path '*isomorphic*' -and ! -path '*qunit*' -and ! -path '*docs*' | xargs -n1 ./modules/org.openbravo.client.kernel/jslint/jslint || exit 1
