#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2019 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************

#
# Mercurial pretxncommit hook to check linting in project root
#
echo "Performing jslint check on modified js resources"
for i in $(hg log -r $HG_NODE --template '{files}')
do
  if [ -f "$i" -a -n "$(echo $i | awk '/.js$/ && ! /^web/')" ]; then
    filefullpath="$(pwd)/${i}"
    ./modules/org.openbravo.client.kernel/jslint/jslint ${filefullpath} || exit 1
  fi
done

exit 0
