#!/bin/bash

echo "Checking --> $@"

if ! [[ -x "$(command -v npm)" ]]; then
    echo -e "\n\033[0;33mERROR:\033[0m npm command not found. Install using"
    echo -e "sudo apt install npm\n";
    exit 1
fi

if [[ ! -d ./modules/org.openbravo.client.kernel/node_modules || -z "$(find ./modules/org.openbravo.client.kernel/node_modules -name eslint)" ]]; then
    echo  "eslint command not found. Running npm install\n"
    originalDir="$(pwd)"
    cd modules/org.openbravo.client.kernel
    npm install
    cd "$originalDir"
fi

npm run jslint --prefix ./modules/org.openbravo.client.kernel -s -- "$(pwd)/$@"
