#!/bin/bash

echo "Checking --> $@"

source ./modules/org.openbravo.client.kernel/jscheck/check-dependencies

npm run jslint --prefix ./modules/org.openbravo.client.kernel -s -- "$@"
#./modules/org.openbravo.client.kernel/node_modules/.bin/eslint -c ./modules/org.openbravo.client.kernel/jslint/.eslintrc.json --max-warnings 0 "$@"
