#!/bin/bash

echo "Checking --> $@"

if [[ ! -d ../org.openbravo.client.kernel/node_modules || -z "$(find ../org.openbravo.client.kernel/node_modules -name eslint)" ]]; then
    echo -e "\n\033[0;33mERROR:\033[0m eslint command not found. Install using \"npm install\" at the root of the project\n"
    exit 1
fi

npm run jslint -s --prefix ../org.openbravo.client.kernel -- "$(pwd)/$@"
