/*
 ************************************************************************************
 * Copyright (C) 2012 Openbravo S.L.U.
 * Licensed under the Openbravo Commercial License version 1.0
 * You may obtain a copy of the License at http://www.openbravo.com/legal/obcl.html
 * or in the legal folder of this module distribution.
 ************************************************************************************
 */

package org.openbravo.retail.posterminal;

import org.openbravo.model.common.invoice.Invoice;

/**
 * Classes extending this class will be executed during the cashup process, for each invoice
 * generated by the OrderGroupingProcessor, after assigning the correct document number.
 * 
 */
public abstract class FinishInvoiceHook {

  public abstract void exec(Invoice invoice, String cashupId) throws Exception;

}