#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2020 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************

CREATE_PACKAGE_JSON_SCRIPT_PATH=modules/org.openbravo.core2/web-jspack/org.openbravo.core2/src/build-scripts/PackageJsonGeneratorLauncher.js
CLEAN_PACKAGE_LOCK_JSON_SCRIPT=modules/org.openbravo.core2/web-jspack/org.openbravo.core2/src/build-scripts/PackageLockJsonCleanerLauncher.js

if [[ -z "$npm_config_module" ]]; then
    echo "module parameter is mandatory" 1>&2
    exit 1
fi
if [ ! -f "$CREATE_PACKAGE_JSON_SCRIPT_PATH" ]; then
    echo "org.openbravo.core2 is not installed, script cannot be executed" 1>&2
    exit 1
fi
if [ ! -d "modules/$npm_config_module/web-jspack/$npm_config_module/" ]; then
    echo "modules/$npm_config_module/web-jspack/$npm_config_module"
    pwd
    echo "No web-jspack folder found on module $npm_config_module, script cannot be executed" 1>&2
    exit 1
fi
echo "Creating package.log"
node $CREATE_PACKAGE_JSON_SCRIPT_PATH --skip-module-dependencies
echo "Executing npm install"
cd "modules/$npm_config_module/web-jspack/$npm_config_module/"
npm install
echo "Removing node_modules"
rm -rf node_modules
cd "../../../../"
echo "Cleaning package-json"
node $CLEAN_PACKAGE_LOCK_JSON_SCRIPT
echo "Running npm install"
npm install





