-- ----------------------------------------------------------------------- 
-- TABLE PLAN_TABLE 
-- ----------------------------------------------------------------------- 
CREATE TABLE PLAN_TABLE
(
    STATEMENT_ID VARCHAR2(30),
    TIMESTAMP DATE,
    REMARKS VARCHAR2(80),
    OPERATION VARCHAR2(30),
    OPTIONS VARCHAR2(255),
    OBJECT_NODE VARCHAR2(128),
    OBJECT_OWNER VARCHAR2(30),
    OBJECT_NAME VARCHAR2(30),
    OBJECT_INSTANCE INTEGER,
    OBJECT_TYPE VARCHAR2(30),
    OPTIMIZER VARCHAR2(255),
    SEARCH_COLUMNS NUMBER,
    ID INTEGER,
    PARENT_ID INTEGER,
    POSITION INTEGER,
    COST INTEGER,
    CARDINALITY INTEGER,
    BYTES INTEGER,
    OTHER_TAG VARCHAR2(255),
    PARTITION_START VARCHAR2(255),
    PARTITION_STOP VARCHAR2(255),
    PARTITION_ID INTEGER,
    OTHER CLOB,
    DISTRIBUTION VARCHAR2(30),
    CPU_COST INTEGER,
    IO_COST INTEGER,
    TEMP_SPACE INTEGER,
    ACCESS_PREDICATES VARCHAR2(4000),
    FILTER_PREDICATES VARCHAR2(4000)
)
/-- END PLAN_TABLE 


CALL DBA_RECOMPILE(NULL)
/-- END

