#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2019 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************

set -e

if ! [[ -x "$(command -v prettier)" ]]; then
    echo -e "\n\033[0;33mERROR:\033[0m prettier command not found. Install using"
    echo -e "# sudo npm install -g prettier@^1.15.3\n"
    exit 1
fi

if ! [[ "$(eslint -v)" =~ ^1.15* ]]; then
    echo -e "\n\033[0;33mWARNING:\033[0m For better compatibility it is recommended to use a 1.x version of prettier\n"
fi

changedfile=$1
replaceparam=$2
prettier --config ../org.openbravo.client.kernel/jsformatter/.prettierrc.json "$changedfile" > "$changedfile.prettier"
if ! diff -u "$changedfile" "$changedfile.prettier"; then
  if [ "$replaceparam" != "replace" ] ; then
    echo ""
    echo "******************************************************************************************************************************************************"
    echo "See above Formatter Error --> Please, format $changedfile";
    echo "******************************************************************************************************************************************************"
    echo ""
    rm -rf "$changedfile.prettier"
    export ERROR="1"
  else
    cat "$changedfile.prettier" > "$changedfile"
    echo "Formatter --> File formatted: $changedfile";
  fi
fi
rm -rf "$changedfile.prettier"
