#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2019 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************

set -e
set -o nounset

source ./modules/org.openbravo.client.kernel/jscheck/check-dependencies

changedfile="$(pwd)/$1"
replaceparam=$2
npm run jsformatter -s --prefix ./modules/org.openbravo.client.kernel -- "$changedfile" > "$changedfile.prettier"
if ! diff -u "$changedfile" "$changedfile.prettier"; then
  if [ "$replaceparam" != "replace" ] ; then
    echo ""
    echo "******************************************************************************************************************************************************"
    echo "See above Formatter Error --> Please, format $changedfile";
    echo "******************************************************************************************************************************************************"
    echo ""
    rm -rf "$changedfile.prettier"
    export ERROR="1"
  else
    cat "$changedfile.prettier" > "$changedfile"
    echo "Formatter --> File formatted: $changedfile";
  fi
fi
rm -rf "$changedfile.prettier"
