#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2019 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************

#
# Mercurial pre-commit hook to check formatting in js code
#
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${SCRIPT_DIR}/../jsutils/dir-functions

KERNEL_MODULE_PATH=$(getKernelModulePath)
IS_A_MODULE=$(isCurrentFolderModuleRoot)

echo "Performing formatting check on modified js resources"
FILES=()
for changedfile in $(hg st -ma)
do
  if [[ -f "${changedfile}" ]]; then
    if [[ "${IS_A_MODULE}" == true && -n "$(echo ${changedfile} | awk '/.js$/')" || \
          "${IS_A_MODULE}" == false && -n "$(echo ${changedfile} | awk '/.js$/ && ! /^web/')" ]]; then
        FILES+=("$(pwd)/${changedfile}")
    fi
  fi
done

if [[ -n "${FILES[*]}" ]]; then
    ${KERNEL_MODULE_PATH}/jsformatter/jsformatter ${FILES[*]} || exit 1
fi

exit 0
