#!/bin/sh

# Find js files

find $1 -name '*.js' -and ! -path '*isomorphic*' \
-and ! -path '*qunit*' -and ! -path '*docs*' \
-and ! -path '*LAB*' -and ! -path '*benchmark*' \
-and ! -path '*unittest*' \
-and ! -path '*postest*' \
-and ! -path '*xmla4js*' \
-and ! -path '*VAADIN*' \
-and ! -path '*saiku*' \
-and ! -path '*libs*' \
-and ! -path '*lib*' \
-and ! -path '*enyo*' \
-and ! -path '*smartclient*' \
-and ! -path '*scopeleaks*' \
-and ! -path '*BigDecimal*'