/*
 ************************************************************************************
 * Copyright (C) 2021 Openbravo S.L.U.
 * Licensed under the Openbravo Commercial License version 1.0
 * You may obtain a copy of the License at http://www.openbravo.com/legal/obcl.html
 * or in the legal folder of this module distribution.
 ************************************************************************************
 */

require('../SetupTicket');
require('../../../../../web/org.openbravo.retail.posterminal/app/model/business-object/ticket/actions/ReturnLine');
require('../SetupTicketUtils');
const deepfreeze = require('deepfreeze');

describe('returnLine', () => {
  test.each`
    lines                                                                 | lineIds       | result
    ${[]}                                                                 | ${[]}         | ${{ lines: [] }}
    ${[{ id: '1', qty: 1 }]}                                              | ${[]}         | ${{ lines: [{ id: '1', qty: 1 }] }}
    ${[{ id: '1', qty: 1 }, { id: '2', qty: 2 }, { id: '3', qty: 3 }]}    | ${['2']}      | ${{ lines: [{ id: '1', qty: 1 }, { id: '2', qty: -2 }, { id: '3', qty: 3 }] }}
    ${[{ id: '1', qty: -1 }, { id: '2', qty: 2 }, { id: '3', qty: -3 }]}  | ${['2']}      | ${{ lines: [{ id: '1', qty: -1 }, { id: '2', qty: -2 }, { id: '3', qty: -3 }] }}
    ${[{ id: '1', qty: 1 }, { id: '2', qty: -2 }, { id: '3', qty: 3 }]}   | ${['2']}      | ${{ lines: [{ id: '1', qty: 1 }, { id: '2', qty: 2 }, { id: '3', qty: 3 }] }}
    ${[{ id: '1', qty: -1 }, { id: '2', qty: -2 }, { id: '3', qty: -3 }]} | ${['2']}      | ${{ lines: [{ id: '1', qty: -1 }, { id: '2', qty: 2 }, { id: '3', qty: -3 }] }}
    ${[{ id: '1', qty: 1 }, { id: '2', qty: 2 }, { id: '3', qty: 3 }]}    | ${['1', '3']} | ${{ lines: [{ id: '1', qty: -1 }, { id: '2', qty: 2 }, { id: '3', qty: -3 }] }}
    ${[{ id: '1', qty: 1 }, { id: '2', qty: -2 }, { id: '3', qty: 3 }]}   | ${['1', '3']} | ${{ lines: [{ id: '1', qty: -1 }, { id: '2', qty: -2 }, { id: '3', qty: -3 }] }}
    ${[{ id: '1', qty: -1 }, { id: '2', qty: 2 }, { id: '3', qty: -3 }]}  | ${['1', '3']} | ${{ lines: [{ id: '1', qty: 1 }, { id: '2', qty: 2 }, { id: '3', qty: 3 }] }}
    ${[{ id: '1', qty: -1 }, { id: '2', qty: -2 }, { id: '3', qty: -3 }]} | ${['1', '3']} | ${{ lines: [{ id: '1', qty: 1 }, { id: '2', qty: -2 }, { id: '3', qty: 3 }] }}
  `('should return defined lines', ({ lines, lineIds, result }) => {
    const ticket = deepfreeze({ lines });
    const payload = deepfreeze({ lineIds, preferences: {} });
    const newTicket = OB.App.StateAPI.Ticket.returnLine(ticket, payload);
    expect(newTicket).toStrictEqual(result);
  });

  test.each`
    lines                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | lineIds  | result
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                             | ${['1']} | ${{ lines: [{ id: '1', qty: 2, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }] }}
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'B', groupProduct: true } }]}                                                                                                                                                                                                                                                             | ${['1']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'B', groupProduct: true } }] }}
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 12, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                             | ${['1']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 12, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 6, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                             | ${['1']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 6, splitline: false, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                            | ${['1']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                              | ${['1']} | ${{ lines: [{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: false } }]}                                                                                                                                                                                                                                                            | ${['1']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: false } }] }}
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: true, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                              | ${['1']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: true, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                             | ${['2']} | ${{ lines: [{ id: '1', qty: 2, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }] }}
    ${[{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'B', groupProduct: true } }]}                                                                                                                                                                                                                                                             | ${['2']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'B', groupProduct: true } }] }}
    ${[{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 12, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                             | ${['2']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 12, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 6, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                             | ${['2']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 6, splitline: false, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                              | ${['2']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                            | ${['2']} | ${{ lines: [{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: false } }]}                                                                                                                                                                                                                                                            | ${['2']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: false } }] }}
    ${[{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: true, product: { id: 'A', groupProduct: true } }]}                                                                                                                                                                                                                                                              | ${['2']} | ${{ lines: [{ id: '1', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: true, product: { id: 'A', groupProduct: true } }] }}
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }, { id: '3', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]}                                                                                                                               | ${['1']} | ${{ lines: [{ id: '1', qty: 3, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }] }}
    ${[{ id: '1', qty: -1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '2', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }, { id: '3', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'B', groupProduct: true } }, { id: '4', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'A', groupProduct: true } }]} | ${['1']} | ${{ lines: [{ id: '1', qty: 3, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, product: { id: 'A' } }, { id: '3', qty: 1, baseGrossUnitPrice: 10, baseNetUnitPrice: 5, splitline: false, product: { id: 'B', groupProduct: true } }] }}
  `('should merge returned lines', ({ lines, lineIds, result }) => {
    const ticket = deepfreeze({ lines });
    const payload = deepfreeze({ lineIds, preferences: {} });
    const newTicket = OB.App.StateAPI.Ticket.returnLine(ticket, payload);
    expect(newTicket).toStrictEqual(result);
  });

  test.each`
    lines                     | lineIds  | notAllowSalesWithReturn | result
    ${[]}                     | ${[]}    | ${false}                | ${{ lines: [] }}
    ${[]}                     | ${[]}    | ${true}                 | ${{ orderType: 0, documentType: 'O', lines: [] }}
    ${[{ id: '1', qty: 1 }]}  | ${[]}    | ${true}                 | ${{ orderType: 0, documentType: 'O', lines: [{ id: '1', qty: 1 }] }}
    ${[{ id: '1', qty: -1 }]} | ${[]}    | ${true}                 | ${{ orderType: 1, documentType: 'R', lines: [{ id: '1', qty: -1 }] }}
    ${[{ id: '1', qty: 1 }]}  | ${['1']} | ${true}                 | ${{ orderType: 1, documentType: 'R', lines: [{ id: '1', qty: -1 }] }}
    ${[{ id: '1', qty: -1 }]} | ${['1']} | ${true}                 | ${{ orderType: 0, documentType: 'O', lines: [{ id: '1', qty: 1 }] }}
  `(
    'should change ticket type',
    ({ lines, lineIds, notAllowSalesWithReturn, result }) => {
      const ticket = deepfreeze({ lines });
      const payload = deepfreeze({
        lineIds,
        preferences: { notAllowSalesWithReturn },
        terminal: {
          terminalType: { documentType: 'O', documentTypeForReturns: 'R' }
        }
      });
      const newTicket = OB.App.StateAPI.Ticket.returnLine(ticket, payload);
      expect(newTicket).toStrictEqual(result);
    }
  );
});
